### PR TITLE
fixes to getRelative

### LINKED ISSUE #163: getRelative time is broken in many cases
1. Most of the locales are missing the `'ss'` relativeTime definition and the `if/then/else` logic misses many edge cases. In fact this logic doesn't closely follow the [Time from now definitions](https://momentjs.com/docs/#/displaying/fromnow/) in moment.js. In addition low numbers of seconds were reported as negative eg. 'in -7 seconds'

I've now fixed these in my fork and added to the unit tests. @fightbulc - if you don't agree with this logic please comment

2. However, this broken logic has also uncovered some failed units tests for Latvian and Russian localisations. I don't speak these languages but I could have a go with Google Translate. But I think my pull request would need some expert review perhaps by @LinMAD and @dypa who made most recent contributions to those locales. @fightbulc - please advise.

I'm ready to submit a pull request for above

### PR DESCRIPTION
**Pull request by blacknell**
closes #163

### CODE REVIEW

File: src/Locales/lv_LV.php [hunk 1]
```diff
@@ -33,7 +33,7 @@
     'relativeTime'  => array(
         'future' => 'pēc %s',
         'past'   => 'pirms %s',
-        's'      => 'sekundes',
+        's'      => 'dažas sekundes',
```
Comment (LinMAD) [inline src/Locales/lv_LV.php]: Better will be: `   's'      => 'dažām sekundēm', `

Comment (blacknell) [reply src/Locales/lv_LV.php]: Done. Thanks @LinMAD.

**Comment by blacknell** [comment]
@fightbulc - could we (you) go ahead and merge this PR please. after this I am going to fix all the other locale missing `'ss'` entries
